pipeline:
  root_src: /home/pdm
  results_root_src: results/trainings
  result_src_name_suffixe: training_with_big_batch_size
  num_loops: 5
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15
  processes:
    upgrade_ground: False
    garbage_as_grey: True
    save_pseudo_labels_per_loop: True
  preload:
    do_continue_from_existing: False
    src_existing: /home/pdm/results/trainings/20250602_175711_training_from_initial_model
  debugging:
    keep_previous_data: False