pipeline:
  root_src: /home/pdm
  results_root_src: results/trainings
  result_src_name_suffixe: test_pseudo_labels_splitting_flatten
  num_loops: 5
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15
  processes:
    upgrade_ground: False
    garbage_as_grey: True
    save_pseudo_labels_per_loop: True
    do_remove_hanging_points: True
    do_flatten: True
    flatten_tile_size: 1
    src_floors: /home/pdm/data/dataset_pipeline/tiles_20/floors
  preload:
    do_continue_from_existing: False
    src_existing: /home/pdm/results/trainings/20250617_133946_test_pseudo_labels_splitting
  debugging:
    keep_previous_data: True