pipeline:
  root_src: /home/pdm
  results_root_src: results/for_paper/others
  result_src_name_suffixe: gs_1_200
  num_loops: 10
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15
  processes:
    upgrade_ground: False
    garbage_as_grey: True
    save_pseudo_labels_per_loop: True
    do_flatten: False
    flatten_tile_size: 10
    src_floors: /home/pdm/data/dataset_pipeline/tiles_20/floors
  preload:
    do_continue_from_existing: True
    src_existing: /home/pdm/results/for_paper/others/20250627_205749_gs_3_500
  debugging:
    keep_previous_data: False
  inference:
    src_existing: results/for_paper/final/final_training
    src_data: data/gt/gt
    results_root_src: results/eval
    result_src_name_suffixe: final_on_gt
    is_gt: True
    with_groups: False
    groups_csv_path: ""  # need to be set if with_groups=True

