pipeline:
  root_src: /home/pdm
  results_root_src: results/trainings
  result_src_name_suffixe: with_instance_splitting
  num_loops: 10
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15
  processes:
    upgrade_ground: False
    garbage_as_grey: True
    save_pseudo_labels_per_loop: True
  preload:
    do_continue_from_existing: True
    src_existing: /home/pdm/results/trainings/20250601_142133_with_instance_splitting