tiles_loader:
  root_src: /home/pdm
  original_file_path: data/multi_tilingsize/color_grp_full_tile_531.laz
  results_destination: data/multi_tilingsize
  tiles_destination: ${tiles_loader.results_destination}/dataset_full_${tiles_loader.tiling.tile_size}
  preprocess:
    do_remove_hanging_points: True
    do_flatten: True
    do_remove_duplicates: True
  tiling:
    tile_size: 20
    pack_size: 1
  trimming:
    method: tree  # choose between {'drop', 'tree'}
    tree_list: [10, 5, 1]  # if method=tree, number of samples per levele
    do_remove_empties: True # use of the classifier to remove the tiles that have no predictions classified as tree
  evaluate:
    run_src: results/trainings_saved/20250601_142133_with_instance_splitting
    cluster_src: data/full_dataset/all_tiles/dataset_full_100m
    cluster_csv_path: data/full_dataset/selection/clustered.csv
    tiles_to_remove: []
    
