tiles_loader:
  root_src: /home/pdm
  original_file_path: data/full_dataset_flat/color_grp_full_flat.las
  results_destination: data/full_dataset/all_tiles/
  tiles_destination: ${tiles_loader.results_destination}/dataset_full_${tiles_loader.tiling.tile_size}m
  preprocess:
    do_flatten: True
    do_remove_duplicates: True
  tiling:
    tile_size: 100
    pack_size: 1
  trimming:
    method: tree  # choose between {'drop', 'tree'}
    tree_list: [10, 5, 1]  # if method=tree, number of samples per levele
    do_remove_empties: True # use of the classifier to remove the tiles that have no predictions classified as tree
